### PR TITLE
TipTap starting point

### PR DESCRIPTION
**Pull request by holtwick**
A quick and dirty hack for showing TipTap integration. Hope this helps as a starting point for a demo. I used this sample code (icons not used): https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Basic/index.vue

### CODE REVIEW

**Comment by dmonad** [comment]
Hey @holtwick , Thanks for this PR! In order to include this example in this repository, I need you to remove the copyright statements and accept the existing license of the repository. Would you be interested to help me to make this a proper demo for the yjs-demos repository?

Looking at the example I think the following things need to be fixed.

- [ ] remove copyright statement
- [ ] install and use y-websocket to make the demo collaborative
- [ ] remove logs
- [ ] Include the y-prosemirror cursor module and include the respective
- [ ] Fix lint issues (`cd yjs-demos && npm run lint`)

Then I will merge this PR and make it available on demos.yjs.dev.

**Comment by holtwick** [comment]
Hi @dmonad. Sure, feel free to remove copyrights and modify everything required. I just left the stuff due to copy pasting in a hurry ;) I can help creating a proper demo, but I'm a bit limited in time right now, so it may take some days. BTW maybe @philippkuehn and other TipTap devs are interested in such a demo as well?

**Comment by holtwick** [comment]
I fixed the issues but didn't get it to work. Probably a trivial thing. Would be great if you could do the rest. Thanks.

**Comment by dmonad** [comment]
Implemented in #14

**Pull request closed without merging**
